### ISSUE TITLE
Mac OS and VS Code while running Prowl.Editor and Prowl.Player

### ISSUE THREAD

**Issue by PaperPrototype** [ProwlEngine/Prowl#49]
**Describe the bug**
### Prowl.Player on MacOS through VS Code

note: vs code will cache the last "Run and Debug" so go to the sidebar to switch between Prowl.Editor and Prowl.Player before running again

**To Reproduce**
1. Go to 'Prowl.Editor/Program.cs'
2. Click 'F5' (on mac you hold the fn key then press F5)
    - If you are doing this for the second time you may get an error **Build Failure** this is because vs code ran Prowl.Editor instead of Prowl.Player '/Users/abdiellopez/Projects/Prowl/Prowl.Editor/Prowl.Editor.csproj' failed to build. Would you like to continue and run the last successful build? if this happens click 'No' -> **To Reproduce (from debug menu)**
5. From the options select 'C#'
6. From the subsequent options select Prowl.Player
7. See error

**To Reproduce (from run and debug menu)**
1. Click 'No' go to the Run and Debug sidebar
2. Select Prowl.Player
3. Go back to Program.cs and click 'F5' (on mac you hold the fn key then press F5)
4. Select C# then Prowl.Player

here is the error

```
Exception has occurred: CLR/System.DllNotFoundException
An unhandled exception of type 'System.DllNotFoundException' occurred in Prowl.Runtime.dll: 'Unable to load shared library 'cimguizmo' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: 
dlopen(/Users/abdiellopez/Projects/Prowl/Prowl.Standalone/bin/Debug/net8.0/runtimes/osx/native/cimguizmo.dylib, 0x0001): tried: '/Users/abdiellopez/Projects/Prowl/Prowl.Standalone/bin/Debug/net8.0/runtimes/osx/native/cimguizmo.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/abdiellopez/Projects/Prowl/Prowl.Standalone/bin/Debug/net8.0/runtimes/osx/native/cimguizmo.dylib' (no such file), '/Users/abdiellopez/Projects/Prowl/Prowl.Standalone/bin/Debug/net8.0/runtimes/osx/native/cimguizmo.dylib' (no such file)
dlopen(/Users/abdiellopez/Projects/Prowl/Prowl.Standalone/bin/Debug/net8.0/runtimes/osx-arm64/native/cimguizmo.dylib, 0x0001): tried: '/Users/abdiellopez/Projects/Prowl/Prowl.Standalone/bin/Debug/net8.0/runtimes/osx-arm64/native/cimguizmo.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/abdiellopez/Projects/Prowl/Prowl.Standalone/bin/Debug/net8.0/runtimes/osx-arm64/native/cimguizmo.dylib' (no such file), '/Users/abdiellopez/Projects/Prowl/Prowl.Standalone/bin/Debug/net8.0/runtimes/osx-arm64/native/cimguizmo.dylib' (no such file)
dlopen(/usr/local/share/dotnet/shared/Microsoft.NETCore.App/8.0.0/cimguizmo.dylib, 0x0001): tried: '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/8.0.0/cimguizmo.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/share/dotnet/shared/Microsoft.NETCore.App/8.0.0/cimguizmo.dylib' (no such file), '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/8.0.0/cimguizmo.dylib' (no such file)
dlopen(/Users/abdiellopez/Projects/Prowl/Prowl.Standalone/bin/Debug/net8.0/cimguizmo.dylib, 0x0001): tried: '/Users/abdiellopez/Projects/Prowl/Prowl.Standalone/bin/Debug/net8.0/cimguizmo.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/abdiellopez/Projects/Prowl/Prowl.Standalone/bin/Debug/net8.0/cimguizmo.dylib' (no such file), '/Users/abdiellopez/Projects/Prowl/Prowl.Standalone/bin/Debug/net8.0/cimguizmo.dylib' (no such file)
dlopen(cimguizmo.dylib, 0x0001): tried: 'cimguizmo.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OScimguizmo.dylib' (no such file), '/usr/lib/cimguizmo.dylib' (no such file, not in dyld cache), 'cimguizmo.dylib' (no such file), '/usr/local/lib/cimguizmo.dylib' (no such file), '/usr/lib/cimguizmo.dylib' (no such file, not in dyld cache)
dlopen(/Users/abdiellopez/Projects/Prowl/Prowl.Standalone/bin/Debug/net8.0/runtimes/osx/native/libcimguizmo.dylib, 0x0001): tried: '/Users/abdiellopez/Projects/Prowl/Prowl.Standalone/bin/Debug/net8.0/runtimes/osx/native/libcimguizmo.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/abdiellopez/Projects/Prowl/Prowl.Standalone/bin/Debug/net8.0/runtimes/osx/native/libcimguizmo.dylib' (no such file), '/Users/abdiellopez/Projects/Prowl/Prowl.Standalone/bin/Debug/net8.0/runtimes/osx/native/libcimguizmo.dylib' (no such file)
dlopen(/Users/abdiellopez/Projects/Prowl/Prowl.Standalone/bin/Debug/net8.0/runtimes/osx-arm64/native/libcimguizmo.dylib, 0x0001): tried: '/Users/abdiellopez/Projects/Prowl/Prowl.Standalone/bin/Debug/net8.0/runtimes/osx-arm64/native/libcimguizmo.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/abdiellopez/Projects/Prowl/Prowl.Standalone/bin/Debug/net8.0/runtimes/osx-arm64/native/libcimguizmo.dylib' (no such file), '/Users/abdiellopez/Projects/Prowl/Prowl.Standalone/bin/Debug/net8.0/runtimes/osx-arm64/native/libcimguizmo.dylib' (no such file)
dlopen(/usr/local/share/dotnet/shared/Microsoft.NETCore.App/8.0.0/libcimguizmo.dylib, 0x0001): tried: '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/8.0.0/libcimguizmo.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/share/dotnet/shared/Microsoft.NETCore.App/8.0.0/libcimguizmo.dylib' (no such file), '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/8.0.0/libcimguizmo.dylib' (no such file)
dlopen(/Users/abdiellopez/Projects/Prowl/Prowl.Standalone/bin/Debug/net8.0/libcimguizmo.dylib, 0x0001): tried: '/Users/abdiellopez/Projects/Prowl/Prowl.Standalone/bin/Debug/net8.0/libcimguizmo.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/abdiellopez/Projects/Prowl/Prowl.Standalone/bin/Debug/net8.0/libcimguizmo.dylib' (no such file), '/Users/abdiellopez/Projects/Prowl/Prowl.Standalone/bin/Debug/net8.0/libcimguizmo.dylib' (no such file)
dlopen(libcimguizmo.dylib, 0x0001): tried: 'libcimguizmo.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibcimguizmo.dylib' (no such file), '/usr/lib/libcimguizmo.dylib' (no such file, not in dyld cache), 'libcimguizmo.dylib' (no such file), '/usr/local/lib/libcimguizmo.dylib' (no such file), '/usr/lib/libcimguizmo.dylib' (no such file, not in dyld cache)
dlopen(/Users/abdiellopez/Projects/Prowl/Prowl.Standalone/bin/Debug/net8.0/runtimes/osx/native/cimguizmo, 0x0001): tried: '/Users/abdiellopez/Projects/Prowl/Prowl.Standalone/bin/Debug/net8.0/runtimes/osx/native/cimguizmo' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/abdiellopez/Projects/Prowl/Prowl.Standalone/bin/Debug/net8.0/runtimes/osx/native/cimguizmo' (no such file), '/Users/abdiellopez/Projects/Prowl/Prowl.Standalone/bin/Debug/net8.0/runtimes/osx/native/cimguizmo' (no such file)
dlopen(/Users/abdiellopez/Projects/Prowl/Prowl.Standalone/bin/Debug/net8.0/runtimes/osx-arm64/native/cimguizmo, 0x0001): tried: '/Users/abdiellopez/Projects/Prowl/Prowl.Standalone/bin/Debug/net8.0/runtimes/osx-arm64/native/cimguizmo' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/abdiellopez/Projects/Prowl/Prowl.Standalone/bin/Debug/net8.0/runtimes/osx-arm64/native/cimguizmo' (no such file), '/Users/abdiellopez/Projects/Prowl/Prowl.Standalone/bin/Debug/net8.0/runtimes/osx-arm64/native/cimguizmo' (no such file)
dlopen(/usr/local/share/dotnet/shared/Microsoft.NETCore.App/8.0.0/cimguizmo, 0x0001): tried: '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/8.0.0/cimguizmo' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/share/dotnet/shared/Microsoft.NETCore.App/8.0.0/cimguizmo' (no such file), '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/8.0.0/cimguizmo' (no such file)
dlopen(/Users/abdiellopez/Projects/Prowl/Prowl.Standalone/bin/Debug/net8.0/cimguizmo, 0x0001): tried: '/Users/abdiellopez/Projects/Prowl/Prowl.Standalone/bin/Debug/net8.0/cimguizmo' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/abdiellopez/Projects/Prowl/Prowl.Standalone/bin/Debug/net8.0/cimguizmo' (no such file), '/Users/abdiellopez/Projects/Prowl/Prowl.Standalone/bin/Debug/net8.0/cimguizmo' (no such file)
dlopen(cimguizmo, 0x0001): tried: 'cimguizmo' (no such file), '/System/Volumes/Preboot/Cryptexes/OScimguizmo' (no such file), '/usr/lib/cimguizmo' (no such file, not in dyld cache), 'cimguizmo' (no such file), '/usr/local/lib/cimguizmo' (no such file), '/usr/lib/cimguizmo' (no such file, not in dyld cache)
dlopen(/Users/abdiellopez/Projects/Prowl/Prowl.Standalone/bin/Debug/net8.0/runtimes/osx/native/libcimguizmo, 0x0001): tried: '/Users/abdiellopez/Projects/Prowl/Prowl.Standalone/bin/Debug/net8.0/runtimes/osx/native/libcimguizmo' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/abdiellopez/Projects/Prowl/Prowl.Standalone/bin/Debug/net8.0/runtimes/osx/native/libcimguizmo' (no such file), '/Users/abdiellopez/Projects/Prowl/Prowl.Standalone/bin/Debug/net8.0/runtimes/osx/native/libcimguizmo' (no such file)
dlopen(/Users/abdiellopez/Projects/Prowl/Prowl.Standalone/bin/Debug/net8.0/runtimes/osx-arm64/native/libcimguizmo, 0x0001): tried: '/Users/abdiellopez/Projects/Prowl/Prowl.Standalone/bin/Debug/net8.0/runtimes/osx-arm64/native/libcimguizmo' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/abdiellopez/Projects/Prowl/Prowl.Standalone/bin/Debug/net8.0/runtimes/osx-arm64/native/libcimguizmo' (no such file), '/Users/abdiellopez/Projects/Prowl/Prowl.Standalone/bin/Debug/net8.0/runtimes/osx-arm64/native/libcimguizmo' (no such file)
dlopen(/usr/local/share/dotnet/shared/Microsoft.NETCore.App/8.0.0/libcimguizmo, 0x0001): tried: '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/8.0.0/libcimguizmo' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/share/dotnet/shared/Microsoft.NETCore.App/8.0.0/libcimguizmo' (no such file), '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/8.0.0/libcimguizmo' (no such file)
dlopen(/Users/abdiellopez/Projects/Prowl/Prowl.Standalone/bin/Debug/net8.0/libcimguizmo, 0x0001): tried: '/Users/abdiellopez/Projects/Prowl/Prowl.Standalone/bin/Debug/net8.0/libcimguizmo' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/abdiellopez/Projects/Prowl/Prowl.Standalone/bin/Debug/net8.0/libcimguizmo' (no such file), '/Users/abdiellopez/Projects/Prowl/Prowl.Standalone/bin/Debug/net8.0/libcimguizmo' (no such file)
dlopen(libcimguizmo, 0x0001): tried: 'libcimguizmo' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibcimguizmo' (no such file), '/usr/lib/libcimguizmo' (no such file, not in dyld cache), 'libcimguizmo' (no such file), '/usr/local/lib/libcimguizmo' (no such file), '/usr/lib/libcimguizmo' (no such file, not in dyld cache)'
   at Prowl.Runtime.ImGUI.ImGuizmo.ImGuizmoNative.ImGuizmo_SetImGuiContext(IntPtr ctx)
   at Prowl.Runtime.ImGUI.ImGuizmo.ImGuizmo.SetImGuiContext(IntPtr ctx) in /Users/abdiellopez/Projects/Prowl/Prowl.Runtime/ImGUI/ImGuizmo/ImGuizmo.gen.cs:line 246
   at Prowl.Runtime.ImGUI.ImGUIController.Load(Int32 width, Int32 height) in /Users/abdiellopez/Projects/Prowl/Prowl.Runtime/ImGUI/ImGUIController.cs:line 62
   at Prowl.Runtime.Application.Initialize() in /Users/abdiellopez/Projects/Prowl/Prowl.Runtime/Application.cs:line 46
   at Prowl.Standalone.Program.Main(String[] args) in /Users/abdiellopez/Projects/Prowl/Prowl.Standalone/Program.cs:line 10
```

**Expected behavior**
I'm not really sure.

**Screenshots**
<img width="1184" alt="Screenshot 2023-11-23 at 10 29 49 AM" src="https://github.com/michaelsakharov/Prowl/assets/48071553/dcd067bc-3178-4aba-914c-a00c4524d323">

**Describe the bug**
## Prowl.Editor on MacOS through VS Code

**To Reproduce**

note: vs code will cache the last "Run and Debug" so go to the sidebar to switch between Prowl.Editor and Prowl.Player before running again

1. Go to 'Prowl.Editor/Program.cs'
2. Click 'F5' (on mac you hold the fn key then press F5)
    - vs code may automatically run Prowl.Player. To switch open the Run and Debug sidebar as mentioned above
    - if this is the case just go open the sidebar and switch, then run Program.cs again and it should run Prowl.Editor
    - see error
5. From the options select 'C#'
6. From the subsequent options select Prowl.Editor
7. See error

here is the error

```
CSC : error CS1566: Error reading resource 'Prowl.Editor.EmbeddedResources.DefaultAssets.Cube.obj' -- 'Could not find file '/Users/abdiellopez/Projects/Prowl/Prowl.Editor/EmbeddedResources/DefaultAssets/Cube.obj'.' [/Users/abdiellopez/Projects/Prowl/Prowl.Editor/Prowl.Editor.csproj]
```

**Expected behavior**
I'm not really sure.

**Desktop (please complete the following information):**
 - OS: Mac OS Sonoma 14.1 running Apple M2 Pro chip
 - Browser why am I being asked this? I use Chrome
 - Version Chrome 119.0.6045.159 (Official Build) (arm64)? XD not sure but ok

**Additional context**

**Comment by PaperPrototype** [comment]
The .gitignore file ingores .obj files which i think is why the Editor fails to run

**Comment by michaelsakharov** [comment]
the missing Default Assets has been fixed, working on the missing dll now

**Comment by michaelsakharov** [comment]
Should be fixed now!

**Comment by PaperPrototype** [comment]
> the missing Default Assets has been fixed, working on the missing dll now

I'm still getting dll issues?

**Comment by michaelsakharov** [comment]
Decided to Re-Open this as it's not fully solved, we know it's because we lack dll's compiled for Apple Silicon/m1+ Mac's.

**Comment by michaelsakharov** [comment]
@PaperPrototype Could you add the DLL files we built into here for future reference?

**Comment by sinnwrig** [comment]
Technically, a similar issue still exists with the native SDL2 DLLs (planning to fix them soon), but since the ImGUI dependency is gone and we don't get this error anymore, should this be best closed?
